### ISSUE TITLE
The letter "J" is ignored

### ISSUE THREAD

**Issue by jhuleatt** [mathemakitten/bad-wolfram-alpha#4]
With this input:

![If Jim has 5 apples, and then gets 5 more, how many apples does he have?](https://i.imgur.com/bwMghh1.png)

The next page shows:

![If im has 5 apples, and then gets 5 more, how many apples does he have?](https://i.imgur.com/8WE2yVs.png)

"Jim" turns into "im"

**Comment by Azhng** [comment]
Looks like `J` is not in the `char2idx.pkl` file. That's why it simply gets dropped from here :https://github.com/mathemakitten/bad-wolfram-alpha/blob/master/app.py#L71 

```
>>> char2idx = pickle.load(open('char2idx.pkl', 'rb'))
>>> char2idx['J']
Traceback (most recent call last):                                                                                  
 File "<stdin>", line 1, in <module>
```

**Comment by mathemakitten** [comment]
Thanks for flagging this! It turns out that "J" has never appeared in our mathematical corpus hehehe. We do have much more data available which I haven't really looked at yet, so that may resolve this easily without any additional case-by-case finagling around the vocabulary. More updates with a model retrain!
